### ISSUE TITLE
APK at releases built for debug?

### ISSUE THREAD

**Issue by IzzySoft** [sagardhadke/LockQR#7]
The APK at releases is built for debug. Is there any reason for that? Shouldn't APKs for distribution come without the debug flag? Just wondering and would appreciate clarification. Thanks!

**Comment by sagardhadke** [comment]
Download The 1.3 APK Form Official site :- https://sagardhadke.github.io/LockQR/
If you are face any error then create again issues i will currently working on 1.4 app version, i hope you love this project 
Thanks :)

**Comment by IzzySoft** [comment]
I'd add your app to [my repo](https://apt.izzysoft.de/fdroid) – but for auto-updates to work I'd need to grab the APK from releases here (or from a "fixed URL"). That was the background of my question. And if you have any questions on this repo, I happily explain – though the [details link](https://apt.izzysoft.de/fdroid/index/info) should explain most stuff.

**Comment by sagardhadke** [comment]
Currently, we not support auto update in app, but you can download relese apk using this link 

Link:- https://github.com/sagardhadke/LockQR/releases/download/1.3/LockQR.apk

you can change only release version like 1.2, 1.3 etc.. this link is fix for downloading apk

**Comment by IzzySoft** [comment]
> Currently, we not support auto update in app

Seems like you misunderstood me. I was talking about the updater in my repo, see above. To have app updates show up in timely manner, it has a daily run where it looks at the app's repos and fetches new releases. To do that it must somehow *know* there are new releases and which – it cannot randomly modify links like that (they are not "fixed" if they have a dynamic part). With far over 1k apps in my repo, I cannot hunt updates manually :wink:

While there are APKs at releases here which my updater would find, those are **debug** builds, as outlined above, signed with a **debug key:**

```
package: name='net.uniquecomputer.lockqr' versionCode='3' versionName='1.3' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Number of signers: 1
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: 584a52f079a60c7f8cae896d3c6c497dfbb35e3859864c0576ff8c9cce794340
Signer #1 certificate SHA-1 digest: 4023beb76e1077fb3a6afae3104c4eb84a02855d
Signer #1 certificate MD5 digest: db00b93564de8f18412461f02fe88064
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

So they are not suitable for distribution. For technical background, see e.g.

* [Why debug certificate is not safe to sign android APKs?](https://stackoverflow.com/q/63497331/2533433)
* [issues when using local debug keystore](https://proandroiddev.com/configuring-android-project-little-things-that-matter-d6a9d34c1ce0?gi=19305d0293a8#1daf)
